<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('occasions', function (Blueprint $table) {
            // Using UUID to match your CgiGeneration structure
            $table->uuid('id')->primary(); 
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            
            // 1. Core Concept & Form Inputs
            $table->string('occasion_identity'); // e.g., Noboborsho
            $table->text('visual_direction');    // e.g., Mangal shobhajatra with a colorful owl mask
            $table->text('custom_text')->nullable(); // e.g., শুভ নববর্ষ
            $table->string('camera_motion')->nullable(); // e.g., Slow Zoom In
            $table->string('motion_intensity')->nullable(); // e.g., Subtle / Ambient
            
            // 2. AI Prompts (Generated by n8n or User)
            $table->text('image_prompt')->nullable();
            $table->text('video_prompt')->nullable();
            $table->text('audio_prompt')->nullable();
            $table->text('negative_prompt')->nullable();
            
            // 3. Status Trackers
            $table->string('status')->default('pending_prompt'); // pending_prompt, completed
            $table->string('image_status')->default('pending'); // pending, making, completed
            $table->string('video_status')->default('pending'); // pending, making, completed
            
            // 4. Final Media URLs
            $table->string('image_url')->nullable();
            $table->string('video_url')->nullable();
            $table->string('branded_image_url')->nullable();
            $table->string('branded_video_url')->nullable();
            
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists('occasions');
    }
};