<?php

$sharedLayoutDirectives = [
    'Produce a clean, photorealistic advertising poster set in a real-life environment.',
    'Then ALSO showcase the actual product as a highlighted hero element, composited cleanly in the bottom-right corner, in sharp focus, sized so it is clearly visible without dominating the scene, while staying clear of the bottom safe strip.',
    'LAYOUT SAFE ZONES (CRITICAL): gently dim and darken a soft, smooth horizontal band across the very TOP of the frame (spanning both top corners) and across the very BOTTOM of the frame, like a subtle dark gradient scrim. Keep these bands muted, low-contrast and free of bright highlights or busy detail, so overlaid brand logos (top) and footer text (bottom) stay clearly visible and easy to read.',
    'Place the marketing headline in the upper-middle area just below the top logo strip, as darker uncluttered negative space.',
    'Render any requested marketing text / selling points as a short, bold, professional headline that is crisp, correctly spelled, well-spaced and non-overlapping; do NOT crowd the image with many bullet points.',
];

return [
    'lighting' => array_merge(require __DIR__ . '/cgi_business/lighting_form.php', [
        'label' => 'Lighting Company',
        'icon' => '💡',
        'step04_label' => 'How is the product used in the scene?',
        'step04_guide' => 'Search and pick the light type and how it is used (e.g. halogen floodlight on a badminton court). Your choice decides which matching scene backgrounds appear in step 05.',
        'step04_search_placeholder' => 'Search light usage...',
        'usage_options' => require __DIR__ . '/cgi_business/lighting_usage.php',
        'brand_directives' => array_merge($sharedLayoutDirectives, [
            'CRITICAL: the same type of lighting product must appear installed and switched ON inside the scene, fitted exactly as it would be in real life (e.g. tube lights mounted on the ceiling, bulbs sitting in pendant or wall fixtures, panel lights recessed in the ceiling, string lights strung across the space), clearly glowing and visibly lighting up the environment so the poster demonstrates the product actually in use.',
            'That installed product is the primary light source: the whole scene must be illuminated naturally and warmly by its own glow, with believable light spill, soft reflections, gentle shadows and a cozy, inviting atmosphere.',
            'Do NOT place any bright lights or product fixtures inside the top and bottom safe bands.',
        ]),
    ]),

    'paint' => [
        'label' => 'Color Company',
        'icon' => '🎨',
        'step01_label' => 'What paint product are you selling?',
        'step01_guide' => 'Name the paint type, finish, and pack size. This helps the AI show the right bucket, tin, and surface finish.',
        'step01_placeholder' => 'E.g. Premium Interior Emulsion 20L...',
        'product_suggestions' => [
            ['icon' => '🏠', 'label' => 'Interior Emulsion', 'value' => 'Premium Interior Emulsion Paint'],
            ['icon' => '🏢', 'label' => 'Exterior Paint', 'value' => 'Weatherproof Exterior Facade Paint'],
            ['icon' => '🪵', 'label' => 'Wood Polish', 'value' => 'Premium Wood Polish & Varnish'],
            ['icon' => '🔩', 'label' => 'Metal Enamel', 'value' => 'Anti-Rust Metal Enamel Paint'],
            ['icon' => '🏠', 'label' => 'Roof Coating', 'value' => 'Waterproof Roof Coating Paint'],
            ['icon' => '✨', 'label' => 'Texture Paint', 'value' => 'Designer Texture Wall Paint'],
            ['icon' => '🎨', 'label' => 'Distemper', 'value' => 'Economy Acrylic Distemper Paint'],
            ['icon' => '🛡️', 'label' => 'Primer', 'value' => 'Wall Primer & Sealer Coat'],
        ],
        'step03_label' => 'Text You Want To See !',
        'step03_guide' => 'Select or type paint benefits you want highlighted as bold headline text on the poster.',
        'step03_placeholder' => 'Type custom paint benefits or select below...',
        'marketing_chips' => [
            ['icon' => '🛡️', 'label' => 'Washable Finish', 'value' => 'WASHABLE & EASY TO CLEAN', 'match' => 'WASHABLE'],
            ['icon' => '🦠', 'label' => 'Anti-Fungal', 'value' => 'ANTI-FUNGAL PROTECTION', 'match' => 'ANTI-FUNGAL'],
            ['icon' => '🌈', 'label' => 'Vibrant Color', 'value' => 'VIBRANT LONG-LASTING COLOR', 'match' => 'VIBRANT'],
            ['icon' => '☀️', 'label' => 'UV Protection', 'value' => 'UV & WEATHER PROTECTION', 'match' => 'UV'],
            ['icon' => '💧', 'label' => 'Waterproof', 'value' => 'WATERPROOF & DAMP RESISTANT', 'match' => 'WATERPROOF'],
            ['icon' => '🌿', 'label' => 'Low Odour', 'value' => 'LOW ODOUR & ECO FRIENDLY', 'match' => 'LOW ODOUR'],
            ['icon' => '⚡', 'label' => 'Quick Dry', 'value' => 'QUICK DRYING FORMULA', 'match' => 'QUICK DRY'],
            ['icon' => '🏠', 'label' => 'Interior & Exterior', 'value' => 'PERFECT FOR INTERIOR & EXTERIOR', 'match' => 'INTERIOR'],
            ['icon' => '💎', 'label' => 'Premium Finish', 'value' => 'SILKY SMOOTH PREMIUM FINISH', 'match' => 'PREMIUM FINISH'],
        ],
        'step04_label' => 'How is the paint applied in the scene?',
        'step04_guide' => 'Search and pick how the paint is used (e.g. interior wall emulsion, exterior facade coating). Your choice decides which matching room or surface backgrounds appear in step 05.',
        'step04_search_placeholder' => 'Search paint application...',
        'usage_options' => [
            [
                'id' => 'Interior Wall',
                'icon' => '🏠',
                'label' => 'Interior Wall Emulsion',
                'val' => 'Fresh emulsion paint smoothly applied on interior walls',
                'keywords' => ['interior', 'wall', 'emulsion', 'room paint'],
                'backgrounds' => [
                    ['label' => '🛋️ Living Room', 'val' => 'Modern living room with freshly painted smooth interior walls and elegant accent color'],
                    ['label' => '🛏️ Bedroom', 'val' => 'Cozy bedroom with beautifully painted walls in soft premium tones'],
                    ['label' => '🍳 Kitchen', 'val' => 'Clean modern kitchen with washable painted walls'],
                    ['label' => '🚿 Washroom', 'val' => 'Bright washroom with moisture-resistant painted walls'],
                    ['label' => '💼 Office Room', 'val' => 'Professional office room with crisp painted walls'],
                ],
            ],
            [
                'id' => 'Exterior Facade',
                'icon' => '🏢',
                'label' => 'Exterior Facade Paint',
                'val' => 'Weatherproof paint applied on building exterior walls',
                'keywords' => ['exterior', 'facade', 'weatherproof', 'outside'],
                'backgrounds' => [
                    ['label' => '🏠 Residential Home', 'val' => 'Beautiful residential home exterior with fresh vibrant facade paint'],
                    ['label' => '🏬 Commercial Building', 'val' => 'Modern commercial building with bold exterior paint finish'],
                    ['label' => '🏘️ Apartment Block', 'val' => 'Apartment building exterior with clean freshly painted walls'],
                    ['label' => '🏡 Villa Front', 'val' => 'Luxury villa front elevation with premium exterior paint'],
                ],
            ],
            [
                'id' => 'Wood Polish',
                'icon' => '🪵',
                'label' => 'Wood Polish / Varnish',
                'val' => 'Rich wood polish or varnish applied on wooden surfaces',
                'keywords' => ['wood', 'polish', 'varnish', 'laminate'],
                'backgrounds' => [
                    ['label' => '🚪 Door & Frame', 'val' => 'Elegant wooden door and frame with rich polished finish'],
                    ['label' => '🪜 Staircase', 'val' => 'Wooden staircase with glossy varnish highlighting natural grain'],
                    ['label' => '🛋️ Living Room Panel', 'val' => 'Living room with polished wooden wall paneling'],
                    ['label' => '🍽️ Dining Furniture', 'val' => 'Dining area with polished wooden table and cabinet surfaces'],
                ],
            ],
            [
                'id' => 'Metal Coating',
                'icon' => '🔩',
                'label' => 'Metal Protective Coating',
                'val' => 'Protective paint coating applied on metal gates, grills, or structures',
                'keywords' => ['metal', 'gate', 'grill', 'rust', 'enamel'],
                'backgrounds' => [
                    ['label' => '🚪 Metal Gate', 'val' => 'Residential entrance with freshly coated metal gate in vibrant color'],
                    ['label' => '🏭 Factory Structure', 'val' => 'Industrial metal structure with durable protective paint coating'],
                    ['label' => '🪜 Balcony Grill', 'val' => 'Balcony with freshly painted metal safety grill'],
                    ['label' => '🅿️ Garage Door', 'val' => 'Garage with smooth enamel-coated metal door'],
                ],
            ],
            [
                'id' => 'Roof Waterproof',
                'icon' => '🏠',
                'label' => 'Roof / Waterproof Coating',
                'val' => 'Waterproof roof or terrace coating applied for protection',
                'keywords' => ['roof', 'waterproof', 'terrace', 'leak'],
                'backgrounds' => [
                    ['label' => '🏠 House Rooftop', 'val' => 'House rooftop with clean waterproof coating finish'],
                    ['label' => '🏢 Flat Terrace', 'val' => 'Commercial flat terrace with professional waterproof coating'],
                    ['label' => '🌧️ Monsoon Ready Home', 'val' => 'Home exterior shown rain-ready with protected roof coating'],
                ],
            ],
            [
                'id' => 'Decorative Texture',
                'icon' => '✨',
                'label' => 'Decorative Texture Paint',
                'val' => 'Decorative texture or designer paint finish on feature walls',
                'keywords' => ['texture', 'designer', 'feature wall', 'royale'],
                'backgrounds' => [
                    ['label' => '🛋️ Feature Wall Living', 'val' => 'Living room with stunning textured designer feature wall'],
                    ['label' => '🛏️ Accent Bedroom', 'val' => 'Bedroom with elegant textured accent wall behind the bed'],
                    ['label' => '🍽️ Dining Feature', 'val' => 'Dining room with premium textured paint on one wall'],
                    ['label' => '🏨 Hotel Lobby Wall', 'val' => 'Hotel lobby with luxurious textured wall finish'],
                ],
            ],
        ],
        'brand_directives' => array_merge($sharedLayoutDirectives, [
            'CRITICAL: show the paint color and finish beautifully applied on realistic surfaces (walls, wood, metal, or exterior facade) so the poster demonstrates real-life usage and coverage quality.',
            'The painted surfaces should look smooth, premium, and true-to-color with natural room lighting and believable material texture.',
            'Include the paint product (bucket, tin, or container) as the hero element in the bottom-right corner alongside the painted environment scene.',
        ]),
    ],

    'furniture' => [
        'label' => 'Furniture Company',
        'icon' => '🪑',
        'step01_label' => 'What furniture are you selling?',
        'step01_guide' => 'Name the furniture piece, material, and style. This helps the AI place it correctly in the room scene.',
        'step01_placeholder' => 'E.g. Premium 3-Seater Fabric Sofa Set...',
        'product_suggestions' => [
            ['icon' => '🛋️', 'label' => 'Sofa Set', 'value' => 'Premium 3-Seater Sofa Set'],
            ['icon' => '🍽️', 'label' => 'Dining Set', 'value' => 'Modern 6-Seater Dining Table Set'],
            ['icon' => '🛏️', 'label' => 'Bed Set', 'value' => 'King Size Bed with Storage'],
            ['icon' => '💼', 'label' => 'Office Desk', 'value' => 'Executive Office Desk & Chair Set'],
            ['icon' => '🚪', 'label' => 'Wardrobe', 'value' => 'Spacious 3-Door Wardrobe Cabinet'],
            ['icon' => '📺', 'label' => 'TV Unit', 'value' => 'Modern TV Console & Wall Unit'],
            ['icon' => '🌳', 'label' => 'Outdoor Set', 'value' => 'Garden Patio Furniture Set'],
            ['icon' => '🪑', 'label' => 'Office Chair', 'value' => 'Ergonomic Mesh Office Chair'],
        ],
        'step03_label' => 'Text You Want To See !',
        'step03_guide' => 'Select or type furniture benefits you want highlighted as bold headline text on the poster.',
        'step03_placeholder' => 'Type custom furniture benefits or select below...',
        'marketing_chips' => [
            ['icon' => '💎', 'label' => 'Premium Design', 'value' => 'PREMIUM MODERN DESIGN', 'match' => 'PREMIUM'],
            ['icon' => '🪵', 'label' => 'Solid Wood', 'value' => 'SOLID WOOD CONSTRUCTION', 'match' => 'SOLID WOOD'],
            ['icon' => '🛋️', 'label' => 'Ergonomic', 'value' => 'ERGONOMIC COMFORT', 'match' => 'ERGONOMIC'],
            ['icon' => '📦', 'label' => 'Smart Storage', 'value' => 'SMART STORAGE SOLUTION', 'match' => 'STORAGE'],
            ['icon' => '✨', 'label' => 'Easy Assembly', 'value' => 'EASY ASSEMBLY & SETUP', 'match' => 'ASSEMBLY'],
            ['icon' => '🏠', 'label' => 'Space Saving', 'value' => 'SPACE-SAVING COMPACT DESIGN', 'match' => 'SPACE-SAVING'],
            ['icon' => '🛡️', 'label' => 'Durable Build', 'value' => 'DURABLE LONG-LASTING BUILD', 'match' => 'DURABLE'],
            ['icon' => '🌿', 'label' => 'Eco Material', 'value' => 'ECO-FRIENDLY MATERIALS', 'match' => 'ECO-FRIENDLY'],
            ['icon' => '🏡', 'label' => 'Home & Office', 'value' => 'PERFECT FOR HOME & OFFICE', 'match' => 'HOME & OFFICE'],
        ],
        'step04_label' => 'How is the furniture placed in the scene?',
        'step04_guide' => 'Search and pick how the furniture is used (e.g. sofa in living room, dining set in dining area). Your choice decides which matching room backgrounds appear in step 05.',
        'step04_search_placeholder' => 'Search furniture placement...',
        'usage_options' => [
            [
                'id' => 'Sofa Set',
                'icon' => '🛋️',
                'label' => 'Sofa / Living Set',
                'val' => 'Sofa set placed as the main seating in the living room',
                'keywords' => ['sofa', 'couch', 'living', 'sectional'],
                'backgrounds' => [
                    ['label' => '🛋️ Modern Living Room', 'val' => 'Stylish modern living room with sofa set as the focal point'],
                    ['label' => '🏢 Office Lounge', 'val' => 'Corporate lounge with premium sofa seating arrangement'],
                    ['label' => '🏨 Hotel Lobby', 'val' => 'Elegant hotel lobby with luxury sofa set'],
                    ['label' => '🪟 Apartment Living', 'val' => 'Compact apartment living room with cozy sofa set'],
                ],
            ],
            [
                'id' => 'Dining Set',
                'icon' => '🍽️',
                'label' => 'Dining Table Set',
                'val' => 'Dining table and chairs arranged for family meals',
                'keywords' => ['dining', 'table', 'chair', 'dinner'],
                'backgrounds' => [
                    ['label' => '👨‍👩‍👧 Family Dining', 'val' => 'Warm family dining room with dining table set ready for meals'],
                    ['label' => '🍽️ Open Kitchen Dining', 'val' => 'Open-plan kitchen with modern dining table set'],
                    ['label' => '🏡 Formal Dining Room', 'val' => 'Formal dining room with elegant table and chair set'],
                ],
            ],
            [
                'id' => 'Bedroom Set',
                'icon' => '🛏️',
                'label' => 'Bed / Bedroom Set',
                'val' => 'Bed and bedroom furniture arranged in a cozy bedroom',
                'keywords' => ['bed', 'bedroom', 'mattress', 'wardrobe'],
                'backgrounds' => [
                    ['label' => '🛏️ Master Bedroom', 'val' => 'Luxury master bedroom with bed set as centerpiece'],
                    ['label' => '🌙 Guest Bedroom', 'val' => 'Cozy guest bedroom with neatly arranged bed furniture'],
                    ['label' => '👶 Kids Bedroom', 'val' => 'Bright kids bedroom with compact bed and storage furniture'],
                ],
            ],
            [
                'id' => 'Office Desk',
                'icon' => '💼',
                'label' => 'Office Desk & Chair',
                'val' => 'Office desk and ergonomic chair set up for work',
                'keywords' => ['desk', 'office', 'chair', 'workstation'],
                'backgrounds' => [
                    ['label' => '💼 Home Office', 'val' => 'Modern home office with desk and chair workstation'],
                    ['label' => '🏢 Corporate Office', 'val' => 'Professional corporate office with executive desk setup'],
                    ['label' => '📚 Study Room', 'val' => 'Study room with functional desk and chair arrangement'],
                ],
            ],
            [
                'id' => 'Wardrobe Storage',
                'icon' => '🚪',
                'label' => 'Wardrobe / Storage',
                'val' => 'Wardrobe or storage unit fitted in the room',
                'keywords' => ['wardrobe', 'cabinet', 'storage', 'almirah'],
                'backgrounds' => [
                    ['label' => '🛏️ Bedroom Wardrobe', 'val' => 'Bedroom with spacious fitted wardrobe storage'],
                    ['label' => '👔 Dressing Area', 'val' => 'Dressing area with elegant wardrobe and storage unit'],
                    ['label' => '🏠 Entryway Storage', 'val' => 'Home entryway with practical storage cabinet furniture'],
                ],
            ],
            [
                'id' => 'Outdoor Furniture',
                'icon' => '🌳',
                'label' => 'Outdoor / Garden Furniture',
                'val' => 'Outdoor furniture placed on patio, balcony, or garden',
                'keywords' => ['outdoor', 'garden', 'patio', 'balcony'],
                'backgrounds' => [
                    ['label' => '🏡 Patio', 'val' => 'Sunny patio with outdoor furniture set arranged comfortably'],
                    ['label' => '🪟 Balcony', 'val' => 'Apartment balcony with compact outdoor seating furniture'],
                    ['label' => '🌳 Garden Terrace', 'val' => 'Garden terrace with outdoor dining or lounge furniture'],
                ],
            ],
        ],
        'brand_directives' => array_merge($sharedLayoutDirectives, [
            'CRITICAL: show the furniture naturally placed and in use within a realistic room setting, sized and positioned as it would be in real life, demonstrating comfort, design, and quality materials.',
            'The room should feel lived-in and aspirational with balanced natural lighting, clean composition, and believable shadows.',
            'Include the furniture product as a highlighted hero element in the bottom-right corner, in sharp focus, while the main scene shows the same furniture beautifully placed in the environment.',
        ]),
    ],

    'pharmaceutical' => [
        'label' => 'Pharmaceutical Company',
        'icon' => '💊',
        'step01_label' => 'What medicine, diagnostic machine, or service are you promoting?',
        'step01_guide' => 'Name the medicine, diagnostic device, or healthcare service. Include model or test type if relevant so the AI shows the correct pack, machine, or clinical setup.',
        'step01_placeholder' => 'E.g. Fully Automatic Hematology Analyzer...',
        'product_suggestions' => [
            ['icon' => '💊', 'label' => 'Tablet / Capsule', 'value' => 'Paracetamol 500mg Tablet Strip'],
            ['icon' => '🍼', 'label' => 'Syrup', 'value' => 'Cough & Cold Relief Syrup 100ml'],
            ['icon' => '💉', 'label' => 'Injection / Vial', 'value' => 'Injectable Antibiotic Vial'],
            ['icon' => '🧴', 'label' => 'Ointment / Cream', 'value' => 'Antiseptic Healing Ointment Tube'],
            ['icon' => '🌬️', 'label' => 'Inhaler', 'value' => 'Asthma Relief Metered-Dose Inhaler'],
            ['icon' => '🩺', 'label' => 'IV Fluid', 'value' => 'Normal Saline IV Infusion Bag'],
            ['icon' => '🩸', 'label' => 'Blood Analyzer', 'value' => 'Fully Automatic Hematology Analyzer'],
            ['icon' => '🧪', 'label' => 'Biochemistry Analyzer', 'value' => 'Clinical Chemistry / Biochemistry Analyzer'],
            ['icon' => '📡', 'label' => 'Ultrasound Scanner', 'value' => 'Digital Diagnostic Ultrasound System'],
            ['icon' => '🩻', 'label' => 'X-Ray / Imaging', 'value' => 'Digital X-Ray Radiography System'],
            ['icon' => '❤️', 'label' => 'ECG Machine', 'value' => '12-Lead Digital ECG / EKG Machine'],
            ['icon' => '🧬', 'label' => 'PCR / Molecular', 'value' => 'Real-Time PCR Molecular Diagnostic System'],
            ['icon' => '🩹', 'label' => 'Rapid Test Kit', 'value' => 'Point-of-Care Rapid Diagnostic Test Kit'],
            ['icon' => '🩺', 'label' => 'BP / Vital Monitor', 'value' => 'Digital Blood Pressure & Vital Signs Monitor'],
        ],
        'step03_label' => 'Text You Want To See !',
        'step03_guide' => 'Select or type medicine or diagnostic benefits you want highlighted as bold headline text on the poster. Keep claims professional and trust-focused.',
        'step03_placeholder' => 'Type custom pharma or diagnostic benefits or select below...',
        'marketing_chips' => [
            ['icon' => '✅', 'label' => 'Clinically Proven', 'value' => 'CLINICALLY PROVEN FORMULA', 'match' => 'CLINICALLY'],
            ['icon' => '⚡', 'label' => 'Fast Relief', 'value' => 'FAST & EFFECTIVE RELIEF', 'match' => 'FAST'],
            ['icon' => '🎯', 'label' => 'Accurate Diagnosis', 'value' => 'ACCURATE & RELIABLE DIAGNOSIS', 'match' => 'ACCURATE'],
            ['icon' => '⏱️', 'label' => 'Fast Test Results', 'value' => 'FAST TEST RESULTS IN MINUTES', 'match' => 'TEST RESULTS'],
            ['icon' => '🔬', 'label' => 'Lab-Grade Precision', 'value' => 'LAB-GRADE PRECISION & ACCURACY', 'match' => 'LAB-GRADE'],
            ['icon' => '🛡️', 'label' => 'Safe & Trusted', 'value' => 'SAFE & TRUSTED QUALITY', 'match' => 'TRUSTED'],
            ['icon' => '🏭', 'label' => 'WHO GMP', 'value' => 'WHO GMP CERTIFIED QUALITY', 'match' => 'GMP'],
            ['icon' => '👨‍⚕️', 'label' => 'Doctor Recommended', 'value' => 'DOCTOR RECOMMENDED BRAND', 'match' => 'DOCTOR'],
            ['icon' => '📍', 'label' => 'Point of Care', 'value' => 'POINT-OF-CARE DIAGNOSTIC SOLUTION', 'match' => 'POINT-OF-CARE'],
            ['icon' => '🔍', 'label' => 'Early Detection', 'value' => 'EARLY DETECTION & PREVENTION', 'match' => 'EARLY DETECTION'],
            ['icon' => '💰', 'label' => 'Affordable Care', 'value' => 'AFFORDABLE HEALTHCARE FOR ALL', 'match' => 'AFFORDABLE'],
            ['icon' => '🌍', 'label' => 'Trusted Worldwide', 'value' => 'TRUSTED BY MILLIONS WORLDWIDE', 'match' => 'WORLDWIDE'],
        ],
        'step04_label' => 'How is the product or diagnostic service shown in the scene?',
        'step04_guide' => 'Search and pick how the medicine, diagnostic machine, or service appears (e.g. pharmacy shelf, pathology lab analyzer, ultrasound screening). Your choice decides which matching scene backgrounds appear in step 05.',
        'step04_search_placeholder' => 'Search medicine or diagnostic usage...',
        'usage_options' => [
            [
                'id' => 'Pharmacy Shelf',
                'icon' => '🏪',
                'label' => 'Pharmacy Shelf Display',
                'val' => 'Medicine pack displayed neatly on a professional pharmacy shelf',
                'keywords' => ['pharmacy', 'shelf', 'chemist', 'drug store'],
                'backgrounds' => [
                    ['label' => '🏪 Retail Pharmacy', 'val' => 'Clean modern retail pharmacy with medicine packs neatly arranged on bright shelves'],
                    ['label' => '🏬 Chain Drugstore', 'val' => 'Well-lit chain pharmacy aisle with organized medicine displays'],
                    ['label' => '🌃 Night Pharmacy', 'val' => 'Trusted neighborhood pharmacy counter with medicine packs on display at night'],
                ],
            ],
            [
                'id' => 'Doctor Prescription',
                'icon' => '👨‍⚕️',
                'label' => 'Doctor Prescription',
                'val' => 'Doctor handing a prescription or recommending the medicine to a patient',
                'keywords' => ['doctor', 'prescription', 'clinic', 'physician'],
                'backgrounds' => [
                    ['label' => '🩺 Clinic Consultation', 'val' => 'Professional doctor consultation room with medicine recommendation on desk'],
                    ['label' => '🏥 Hospital OPD', 'val' => 'Hospital outpatient desk with doctor advising patient on prescribed medicine'],
                    ['label' => '💼 Private Chamber', 'val' => 'Private doctor chamber with prescription pad and medicine pack on table'],
                ],
            ],
            [
                'id' => 'Patient Home',
                'icon' => '🏠',
                'label' => 'Patient Home Use',
                'val' => 'Patient safely using the medicine at home as directed',
                'keywords' => ['home', 'patient', 'family', 'recovery'],
                'backgrounds' => [
                    ['label' => '🛋️ Living Room Recovery', 'val' => 'Warm home living room with patient taking medicine comfortably during recovery'],
                    ['label' => '🛏️ Bedside Care', 'val' => 'Cozy bedroom bedside scene with medicine and glass of water on nightstand'],
                    ['label' => '👨‍👩‍👧 Family Health', 'val' => 'Caring family home setting with medicine used for everyday health support'],
                ],
            ],
            [
                'id' => 'Pathology Lab',
                'icon' => '🧪',
                'label' => 'Pathology / Lab Analyzer',
                'val' => 'Diagnostic analyzer machine running tests in a clinical pathology laboratory',
                'keywords' => ['pathology', 'lab', 'analyzer', 'hematology', 'biochemistry', 'blood test'],
                'backgrounds' => [
                    ['label' => '🔬 Diagnostic Lab', 'val' => 'Modern pathology laboratory with diagnostic analyzer processing patient samples'],
                    ['label' => '🩸 Sample Processing', 'val' => 'Clinical lab bench with blood samples and automated diagnostic analyzer in operation'],
                    ['label' => '🏥 Hospital Lab', 'val' => 'Hospital diagnostic laboratory with technician operating advanced analyzer machine'],
                ],
            ],
            [
                'id' => 'Ultrasound Screening',
                'icon' => '📡',
                'label' => 'Ultrasound / Imaging Room',
                'val' => 'Diagnostic ultrasound or imaging machine used for patient screening',
                'keywords' => ['ultrasound', 'sonography', 'imaging', 'radiology', 'scan'],
                'backgrounds' => [
                    ['label' => '📡 Ultrasound Room', 'val' => 'Clean ultrasound screening room with diagnostic imaging machine and patient bed'],
                    ['label' => '🤰 Maternity Scan', 'val' => 'Maternity clinic ultrasound room with sonography machine performing diagnostic scan'],
                    ['label' => '🏥 Imaging Department', 'val' => 'Hospital imaging department with modern diagnostic ultrasound system in use'],
                ],
            ],
            [
                'id' => 'X-Ray Radiology',
                'icon' => '🩻',
                'label' => 'X-Ray / Radiology',
                'val' => 'Digital X-ray or radiology system used for diagnostic imaging',
                'keywords' => ['x-ray', 'xray', 'radiology', 'radiography', 'imaging'],
                'backgrounds' => [
                    ['label' => '🩻 X-Ray Room', 'val' => 'Professional radiology room with digital X-ray machine ready for diagnostic imaging'],
                    ['label' => '🏥 Radiology Department', 'val' => 'Hospital radiology department with advanced diagnostic imaging equipment'],
                    ['label' => '🦴 Orthopedic Scan', 'val' => 'Orthopedic clinic with X-ray system used for bone and joint diagnosis'],
                ],
            ],
            [
                'id' => 'ECG Cardiac',
                'icon' => '❤️',
                'label' => 'ECG / Cardiac Screening',
                'val' => 'ECG machine used for heart monitoring and cardiac diagnosis',
                'keywords' => ['ecg', 'ekg', 'cardiac', 'heart', 'cardiology'],
                'backgrounds' => [
                    ['label' => '❤️ Cardiology Clinic', 'val' => 'Cardiology clinic with ECG machine performing heart diagnostic screening'],
                    ['label' => '🏥 Emergency Cardiac', 'val' => 'Hospital emergency unit with portable ECG monitor for rapid cardiac diagnosis'],
                    ['label' => '👴 Health Checkup', 'val' => 'Community health checkup booth with ECG machine for cardiac screening'],
                ],
            ],
            [
                'id' => 'Point of Care',
                'icon' => '🩹',
                'label' => 'Point-of-Care Testing',
                'val' => 'Rapid diagnostic test or portable device used at bedside or clinic counter',
                'keywords' => ['rapid test', 'point of care', 'portable', 'screening', 'poct'],
                'backgrounds' => [
                    ['label' => '🩺 Clinic Counter', 'val' => 'Primary care clinic counter with rapid diagnostic test kit delivering instant results'],
                    ['label' => '🏪 Pharmacy Screening', 'val' => 'Pharmacy health screening corner with point-of-care diagnostic device'],
                    ['label' => '🎪 Screening Camp', 'val' => 'Community screening camp with portable diagnostic device testing patients on site'],
                ],
            ],
            [
                'id' => 'Diagnostic Center',
                'icon' => '🏥',
                'label' => 'Diagnostic Center Service',
                'val' => 'Full diagnostic center offering multiple test services with professional equipment',
                'keywords' => ['diagnostic center', 'pathology center', 'lab service', 'health checkup'],
                'backgrounds' => [
                    ['label' => '🏥 Diagnostic Center', 'val' => 'Modern diagnostic center reception and testing area with multiple machines and professional staff'],
                    ['label' => '📋 Health Checkup Package', 'val' => 'Premium health checkup diagnostic center with patient-friendly testing environment'],
                    ['label' => '🏢 Corporate Screening', 'val' => 'Corporate health screening diagnostic center with organized test stations and equipment'],
                ],
            ],
            [
                'id' => 'Hospital Ward',
                'icon' => '🏥',
                'label' => 'Hospital Ward / Nursing',
                'val' => 'Medicine or bedside diagnostic monitor used in a clean hospital ward setting',
                'keywords' => ['hospital', 'ward', 'nurse', 'iv', 'monitor'],
                'backgrounds' => [
                    ['label' => '🏥 Hospital Ward', 'val' => 'Clean hospital ward with nurse preparing medicine and vital signs monitor at bedside'],
                    ['label' => '💉 Treatment Room', 'val' => 'Sterile hospital treatment room with medicine vials and diagnostic monitoring equipment'],
                    ['label' => '🚑 Emergency Care', 'val' => 'Modern emergency care unit with diagnostic monitors and medicine ready for urgent treatment'],
                ],
            ],
            [
                'id' => 'Pharmacist Counseling',
                'icon' => '💬',
                'label' => 'Pharmacist Counseling',
                'val' => 'Pharmacist explaining medicine usage to a customer at the counter',
                'keywords' => ['pharmacist', 'counseling', 'counter', 'advice'],
                'backgrounds' => [
                    ['label' => '🏪 Pharmacy Counter', 'val' => 'Friendly pharmacist at pharmacy counter explaining medicine usage to customer'],
                    ['label' => '📋 Medicine Guidance', 'val' => 'Pharmacy consultation desk with pharmacist reviewing medicine leaflet with customer'],
                    ['label' => '👴 Elder Care Advice', 'val' => 'Pharmacist gently advising elderly customer on proper medicine use at counter'],
                ],
            ],
            [
                'id' => 'Health Camp',
                'icon' => '🎪',
                'label' => 'Health Camp / CSR',
                'val' => 'Medicine or diagnostic screening offered at a community health camp',
                'keywords' => ['health camp', 'csr', 'community', 'awareness', 'screening'],
                'backgrounds' => [
                    ['label' => '🎪 Community Health Camp', 'val' => 'Outdoor community health camp with diagnostic screening and medicine awareness banners'],
                    ['label' => '🏫 School Health Program', 'val' => 'School health program booth with diagnostic screening and wellness information display'],
                    ['label' => '🏘️ Rural Outreach', 'val' => 'Rural health outreach camp with portable diagnostic equipment serving community members'],
                ],
            ],
            [
                'id' => 'Lab Quality',
                'icon' => '🔬',
                'label' => 'Lab / Quality Assurance',
                'val' => 'Pharmaceutical or diagnostic product shown in a premium laboratory quality setting',
                'keywords' => ['lab', 'quality', 'research', 'gmp', 'molecular', 'pcr'],
                'backgrounds' => [
                    ['label' => '🔬 R&D Laboratory', 'val' => 'Modern pharmaceutical R&D laboratory with diagnostic product and quality testing environment'],
                    ['label' => '🏭 GMP Production', 'val' => 'Clean GMP-certified facility with pharmaceutical or diagnostic manufacturing focus'],
                    ['label' => '🧬 Molecular Lab', 'val' => 'Advanced molecular diagnostic laboratory with PCR system and precision testing setup'],
                ],
            ],
        ],
        'brand_directives' => array_merge($sharedLayoutDirectives, [
            'CRITICAL: show the pharmaceutical product, diagnostic machine, or healthcare service in a clean, trustworthy, professional medical context (pharmacy, clinic, pathology lab, imaging room, diagnostic center, hospital, or responsible home use) with clinical lighting and a credible healthcare atmosphere.',
            'For medicines: packaging must look crisp, legible, and premium with accurate dosage-form appearance (strip, bottle, vial, tube, inhaler, or device as appropriate).',
            'For diagnostic machines and services: show the equipment realistically installed and in use — analyzer on lab bench, ultrasound or X-ray in imaging room, ECG at bedside, or rapid test at screening counter — demonstrating accurate diagnosis and professional operation.',
            'Maintain a dignified, hopeful, health-positive tone — never fear-mongering, graphic illness imagery, or exaggerated miracle claims.',
            'Include the product (medicine pack or diagnostic device) as the highlighted hero element in the bottom-right corner, in sharp focus, while the main scene demonstrates real-world trust, diagnosis, or care.',
        ]),
    ],
];
