<?php

/**
 * Semantic poster intelligence — every visual layer and text zone must carry meaning.
 * Reference quality: FIFA World Cup 2026 (stadium story + trophy hero + "26" graphic + purposeful footer).
 */
return [
    'semanticPosterFramework' => 'DESIGN LIKE A SENIOR GRAPHIC DESIGNER WHERE EVERY ELEMENT HAS MEANING—nothing decorative without purpose. Layer 1 BACKGROUND STORY: environment that explains the occasion (stadium=global sport, Shaheed Minar=language martyrs, mosque night=Ramadan peace). Layer 2 HERO ICON: one unmistakable 3D or photographic symbol (trophy, monument, diya, ribbon) as the emotional spine. Layer 3 GRAPHIC DEVICE: bold shape or numeral tied to the event (year "26", flag geometry, Alpana ring, crescent arc)—flat minimalist contrast on cinematic photo. Layer 4 COLOR SYMBOLISM: palette encodes emotion (gold=triumph, green-red=Bangladesh pride, pink=awareness, clinical teal=health trust). Layer 5 TYPOGRAPHY ZONES (empty in image): top=identity headline, middle pocket=sub-brand or verse, bottom=factual footer (dates, hosts, CTA)—each future Bangla/English line must map to one zone. Compose: photo depth + graphic flatness + hyper-real hero overlay. Landscape 16:9 only.',

    'semanticCategoryTemplates' => [
        'sports_event' => 'Background=authentic venue atmosphere (pitch, court, track) at dramatic light. Hero=championship trophy or iconic sports object as 3D spine. Graphic=year numeral or scoreboard geometry in bold flat white. Colors=energy (green pitch, gold victory, electric floodlights). Footer zone=dates, teams, or celebration CTA—every line factual.',
        'patriotic_tribute' => 'Background=solemn national landscape or night sky—not festive party. Hero=monument, memorial, or Shaheed Minar with respectful scale. Graphic=flag color geometry or liberation motif—restrained. Colors=green-red-gold Bangladesh dignity or mourning grey-black. Footer zone=verse, date (26 March / 16 December / 21 February)—reverent typography only.',
        'islamic_festival' => 'Background=peaceful night sky, mosque silhouette, or warm family gathering—never cluttered. Hero=crescent, lantern, or shared meal symbol. Graphic=geometric arabesque arc or soft gold halo. Colors=indigo peace, gold blessing, cream warmth. Footer zone=prayer wish, Hijri/Gregorian date, community blessing—respectful not commercial.',
        'hindu_festival' => 'Background=temple courtyard, riverbank, or festive night glow. Hero=diya, dhunuchi, goddess silhouette, or gulal burst frozen in time. Graphic=rangoli ring or mandala fragment as flat accent. Colors=crimson-gold-marigold celebration. Footer zone=festival name, subho shubhechha, community joy—vibrant but legible.',
        'folk_spring' => 'Background=Bengali spring sky, paddy horizon, or folk procession context. Hero=mask, marigold, flute, or Bosonto bird—cultural not generic. Graphic=Alpana base pattern or bold Bengali new-year numeral. Colors=sky-blue, red-green-yellow folk pigments. Footer zone=নববর্ষ greeting, year in Bengali calendar—joyful cultural pride.',
        'health_pharma' => 'Background=clean clinical gradient or hopeful sunrise wellness scene. Hero=ribbon, organ symbol, stethoscope, or product packshot with trust lighting. Graphic=molecule hex, ECG line, or shield emblem at low opacity. Colors=teal trust, navy credibility, cause ribbon accent. Footer zone=awareness message, screening CTA, WHO/campaign date—dignified never fear-mongering.',
        'retail_promo' => 'Background=dark luxury or explosive gradient for offer contrast. Hero=gift box, percent burst, or product hero shot. Graphic=skewed sale shape or date numeral (11.11). Colors=urgency yellow-black or brand neon. Footer zone=offer terms, deadline, shop-now CTA—clear commercial hierarchy.',
        'corporate_industry' => 'Background=glass tower, factory dawn, field horizon, or tech skyline—sector-specific. Hero=sector icon (loom, tower crane, 5G wave, rice sheaf) in premium 3D. Graphic=minimal gold line or growth arrow geometry. Colors=executive navy-gold or sector safety orange. Footer zone=CEO message, summit date, project name—Swiss-grid professionalism.',
        'family_love' => 'Background=golden-hour intimacy or soft pastel environment. Hero=embrace silhouette, roses, or hands bonding. Graphic=heart negative space or gentle arc. Colors=rose, amber, blush warmth. Footer zone=relationship honour, name line, warm wish—emotional not cheesy.',
        'global_celebration' => 'Background=occasion-specific world context (fireworks city, snow village, harvest table). Hero=one global icon (tree, champagne, pumpkin, disco ball). Graphic=year numeral or holiday shape. Colors=occasion-coded globally recognisable palette. Footer zone=greeting, year, togetherness message.',
        'mourning_solemn' => 'Background=muted grey gradient, candlelight, or overcast dawn—zero celebration. Hero=black ribbon, candle, book, or cross silhouette. Graphic=minimal single line or none. Colors=grey, black, white restraint. Footer zone=remembrance verse only—quiet spacing.',
        'nature_season' => 'Background=season truth (monsoon rain, kashful field, beach sun, earth reflection). Hero=leaf, umbrella, wave, or planet. Graphic=soft horizon band for text. Colors=seasonal natural pigments. Footer zone=eco message or season greeting tied to climate.',
        'education_culture' => 'Background=library, classroom warmth, or travel vista. Hero=globe, book stack, passport, or chess piece. Graphic=line-art learning motif. Colors=emerald intellectual or pastel wanderlust. Footer zone=thank-you, literacy slogan, event date.',
        'modern_celebration' => 'Background=unique to occasion name—research what this event means culturally. Hero=single most recognisable symbol worldwide for this event. Graphic=year or abstract shape encoding the mood. Colors=match emotion of the occasion. Footer zone=each overlay line answers: what, when, why celebrate—no filler words.',
    ],

    'semanticCategoryByOccasion' => [
        'FIFA World Cup 2026' => 'sports_event',
        'Football World Cup Fever' => 'sports_event',
        'Cricket Victory Celebration' => 'sports_event',
        'National Sports Day' => 'sports_event',
        'Olympic Spirit Day' => 'sports_event',
        'World Athletics Day' => 'sports_event',
        'Victory Day' => 'patriotic_tribute',
        'Independence Day' => 'patriotic_tribute',
        'International Mother Language Day' => 'patriotic_tribute',
        'National Mourning Day' => 'patriotic_tribute',
        'Martyred Intellectuals Day' => 'patriotic_tribute',
        'Bangabandhu Homecoming Day' => 'patriotic_tribute',
        'Independence Day India' => 'patriotic_tribute',
        'Human Rights Day' => 'patriotic_tribute',
        'Ramadan Kareem' => 'islamic_festival',
        'Eid ul-Fitr' => 'islamic_festival',
        'Eid ul-Adha' => 'islamic_festival',
        'Chand Raat' => 'islamic_festival',
        'Shab-e-Barat' => 'islamic_festival',
        'Islamic New Year' => 'islamic_festival',
        'Ashura (10 Muharram)' => 'mourning_solemn',
        'Laylat al-Qadr (Shab-e-Qadr)' => 'islamic_festival',
        'Laylat al-Miraj' => 'islamic_festival',
        'Shab-e-Meraj' => 'islamic_festival',
        'Jummah tul-Wida' => 'islamic_festival',
        'Milad un-Nabi (Eid-e-Milad)' => 'islamic_festival',
        'Mawlid Celebration' => 'islamic_festival',
        'Hajj Season' => 'islamic_festival',
        'Qurbani Awareness' => 'islamic_festival',
        'Ramadan Iftar Campaign' => 'islamic_festival',
        'Eid Mega Sale' => 'retail_promo',
        'Holi Festival' => 'hindu_festival',
        'Diwali Festival' => 'hindu_festival',
        'Durga Puja' => 'hindu_festival',
        'Lakshmi Puja' => 'hindu_festival',
        'Kali Puja' => 'hindu_festival',
        'Navratri' => 'hindu_festival',
        'Bhai Phota (Bhai Dooj)' => 'hindu_festival',
        'Raksha Bandhan' => 'hindu_festival',
        'Janmashtami' => 'hindu_festival',
        'Maha Shivratri' => 'hindu_festival',
        'Chhath Puja' => 'hindu_festival',
        'Karwa Chauth' => 'hindu_festival',
        'Guru Purnima' => 'hindu_festival',
        'Onam Festival' => 'hindu_festival',
        'Saraswati Puja (Basant Panchami)' => 'hindu_festival',
        'Ugadi' => 'hindu_festival',
        'Pohela Boishakh' => 'folk_spring',
        'Pahela Falgun' => 'folk_spring',
        'Spring Festival (Bosonto)' => 'folk_spring',
        'Makar Sankranti' => 'folk_spring',
        'Lohri' => 'folk_spring',
        'Pongal' => 'folk_spring',
        'World Health Day' => 'health_pharma',
        'World TB Day' => 'health_pharma',
        'World Malaria Day' => 'health_pharma',
        'World Immunization Week' => 'health_pharma',
        'International Nurses Day' => 'health_pharma',
        'World Heart Day' => 'health_pharma',
        'World Pharmacists Day' => 'health_pharma',
        'World Mental Health Day' => 'health_pharma',
        'World Cancer Awareness' => 'health_pharma',
        'World Diabetes Day' => 'health_pharma',
        'World AIDS Day' => 'health_pharma',
        'World ORS Day' => 'health_pharma',
        'Hand Hygiene Day' => 'health_pharma',
        'National Vitamin-A Campaign' => 'health_pharma',
        'Blood Donation Day' => 'health_pharma',
        'Doctor\'s Day Bangladesh' => 'health_pharma',
        'Antibiotic Awareness Week' => 'health_pharma',
        'Pharmacy Week Bangladesh' => 'health_pharma',
        'Generic Medicine Awareness' => 'health_pharma',
        'Pharma Product Launch' => 'health_pharma',
        'CSR Health Camp' => 'health_pharma',
        'World Kidney Day' => 'health_pharma',
        'World Leprosy Day' => 'health_pharma',
        'World Parkinson\'s Day' => 'health_pharma',
        'Lung Health Awareness' => 'health_pharma',
        'World Mental Health Week' => 'health_pharma',
        'World Hepatitis Day' => 'health_pharma',
        'World Hypertension Day' => 'health_pharma',
        'World Sight Day' => 'health_pharma',
        'World Stroke Day' => 'health_pharma',
        'World Prematurity Day' => 'health_pharma',
        'Breast Cancer Awareness Month' => 'health_pharma',
        'Breastfeeding Week' => 'health_pharma',
        'National Nutrition Week' => 'health_pharma',
        'World Suicide Prevention Day' => 'health_pharma',
        'World Alzheimer\'s Day' => 'health_pharma',
        'Autism Awareness Day' => 'health_pharma',
        'Rare Disease Day' => 'health_pharma',
        'World Cancer Day (4 Feb)' => 'health_pharma',
        'World Oral Health Day' => 'health_pharma',
        'World Blood Donor Day' => 'health_pharma',
        'World Sleep Day' => 'health_pharma',
        'Product Awareness Campaign' => 'health_pharma',
        'Black Friday' => 'retail_promo',
        'Cyber Monday' => 'retail_promo',
        'Singles Day (11.11)' => 'retail_promo',
        'FMCG Mega Promo' => 'retail_promo',
        'Puja Mega Sale' => 'retail_promo',
        'Summer Mega Sale' => 'retail_promo',
        'Winter Mega Sale' => 'retail_promo',
        'Flash Sale Weekend' => 'retail_promo',
        'Grand Opening Sale' => 'retail_promo',
        'New Store Opening' => 'retail_promo',
        'Brand Anniversary Sale' => 'retail_promo',
        'Cashback Festival' => 'retail_promo',
        'Eid Shopping Festival' => 'retail_promo',
        'Corporate Anniversary' => 'corporate_industry',
        'Employee Appreciation Day' => 'corporate_industry',
        'Quality Excellence Day' => 'corporate_industry',
        'Garments & Textile Expo' => 'corporate_industry',
        'Agro & Fertilizer Season' => 'corporate_industry',
        'Telecom 5G Launch' => 'corporate_industry',
        'Real Estate Project Launch' => 'corporate_industry',
        'Insurance Awareness Day' => 'corporate_industry',
        'Banking & Finance Day' => 'corporate_industry',
        'Export Summit Bangladesh' => 'corporate_industry',
        'Digital Bangladesh Day' => 'corporate_industry',
        'Startup Innovation Day' => 'corporate_industry',
        'Construction Safety Week' => 'corporate_industry',
        'Factory Safety Day' => 'corporate_industry',
        'ISO Certification Celebration' => 'corporate_industry',
        'CSR Tree Plantation Day' => 'corporate_industry',
        'Valentine\'s Day' => 'family_love',
        'Mother\'s Day' => 'family_love',
        'Father\'s Day' => 'family_love',
        'Friendship Day' => 'family_love',
        'International Women\'s Day' => 'family_love',
        'International Day of Families' => 'family_love',
        'Wedding Season Campaign' => 'family_love',
        'Wedding Invitation Design' => 'family_love',
        'Iftar Party Invitation' => 'family_love',
        'Happy New Year' => 'global_celebration',
        'New Year\'s Eve' => 'global_celebration',
        'Chinese New Year' => 'global_celebration',
        'Merry Christmas' => 'global_celebration',
        'Christmas Eve' => 'global_celebration',
        'Orthodox Christmas' => 'global_celebration',
        'Easter Sunday' => 'global_celebration',
        'Halloween' => 'global_celebration',
        'Thanksgiving' => 'global_celebration',
        'Buddha Purnima' => 'global_celebration',
        'Gandhi Jayanti' => 'global_celebration',
        'International Day of Happiness' => 'global_celebration',
        'Good Friday' => 'mourning_solemn',
        'Earth Day' => 'nature_season',
        'World Environment Day' => 'nature_season',
        'Monsoon Festival' => 'nature_season',
        'Summer Vibes' => 'nature_season',
        'Autumn Festival (Kashful)' => 'nature_season',
        'World Water Day' => 'nature_season',
        'World Food Day' => 'nature_season',
        'International Yoga Day' => 'nature_season',
        'Teacher\'s Day' => 'education_culture',
        'World Teachers Day' => 'education_culture',
        'World Tourism Day' => 'education_culture',
        'World Book Day' => 'education_culture',
        'International Literacy Day' => 'education_culture',
        'International Chess Day' => 'education_culture',
        'World Photography Day' => 'education_culture',
        'World Radio Day' => 'education_culture',
        'International Day of Peace' => 'education_culture',
        'Labour Day' => 'corporate_industry',
        'National Children\'s Day' => 'family_love',
        'World Children\'s Day' => 'family_love',
        'International Youth Day' => 'family_love',
        'International Men\'s Day' => 'family_love',
        'International Day of the Girl Child' => 'family_love',
        'International Day of Persons with Disabilities' => 'education_culture',
        'World Refugee Day' => 'education_culture',
        'World Population Day' => 'education_culture',
        'International Day of the Midwife' => 'health_pharma',
        'Back to School Campaign' => 'education_culture',
        'Default Custom Event' => 'modern_celebration',
    ],

    'semanticOccasionDetail' => [
        'FIFA World Cup 2026' => 'REFERENCE-GRADE SEMANTIC POSTER: (1) Background=high-angle night stadium—floodlit vivid green pitch, dark stands, global football theatre; encodes USA·Canada·Mexico 2026 hosts without flag clutter. (2) Hero=photoreal gold FIFA World Cup trophy centred as vertical spine—world unity, championship glory, metallic reflections. (3) Graphic=bold flat white block numerals "26" behind trophy; trophy pierces numerals like premium broadcast sports graphics—year is the design device. (4) Colors: gold=triumph, pitch green=life of the game, white=official clarity, dark navy=night drama and text contrast. (5) Empty zones: top=title "World Cup 2026"; numeral pocket=sub-brand word; bottom=host nations + dates (11 June–19 July style)—every overlay line must be factual (who, where, when, wish). Layering: cinematic photo + flat typography shape + 3D trophy overlay. NO random confetti without purpose.',

        'Victory Day' => 'Background=starfield night over memorial grounds—solemn victory not party. Hero=Jatiyo Smriti Soudho with cyan rim glow—martyrs honoured. Graphic=subtle "16" or victory star geometry in negative space. Colors=green-red national pride, cyan glow=eternal flame. Footer=16 December, বিজয় দিবস, জয় বাংলা—each line a historical fact.',

        'Independence Day' => 'Background=dawn liberation sky. Hero=white National Martyrs Memorial with crowd silhouettes and detailed flag—1971 spirit. Graphic=flag triangle geometry left third. Colors=green-red-gold freedom. Footer=26 March, স্বাধীনতা দিবস—freedom narrative only.',

        'International Mother Language Day' => 'Background=purple dawn at Shaheed Minar. Hero=monument steps with optional marigolds—language martyrs. Graphic=21 shape or book-page arc. Colors=martyr purple, marigold respect. Footer=আমার ভাইয়ের রক্তে রাঙানো একুশে—poetic verse zone.',

        'Pohela Boishakh' => 'Background=bright sky-blue folk morning—not night city. Hero=green owl mask + white tiger mask + owl fans on Alpana—Mangal Shobhajatra DNA. Graphic=Bengali new-year numeral or Alpana ring base. Colors=folk red-green-yellow pigments. Footer=শুভ নববর্ষ, Bengali year—cultural joy.',

        'Eid ul-Fitr' => 'Background=warm night skyline with fairy lights. Hero=families sharing sweets under crescent—unity after Ramadan. Graphic=crescent arc gold. Colors=gold blessing, navy peaceful night. Footer=ঈদ মোবারক—gratitude and community.',

        'Eid ul-Adha' => 'Background=festive evening with soft city glow. Hero=white goat and family preparation—Qurbani sacrifice spirit. Graphic=crescent and minaret silhouette restrained. Colors=warm gold, white purity. Footer=ঈদুল আযহা শুভেচ্ছা—faith and sharing.',

        'Ramadan Kareem' => 'Background=peaceful indigo night with mosque arch. Hero=brass lantern glow—fasting devotion. Graphic=geometric arabesque window pattern. Colors=indigo peace, gold spiritual light. Footer=রমজান কারীম—blessing and patience.',

        'Holi Festival' => 'Background=dark contrast for color pop. Hero=frozen gulal explosion mid-air—joy release. Graphic=color arc trajectory lines. Colors=magenta cyan yellow pure pigment. Footer=শুভ হোলি—celebration of spring and unity.',

        'Diwali Festival' => 'Background=dark courtyard depth. Hero=symmetric glowing diyas and rangoli—light over darkness. Graphic=mandala fragment flat gold. Colors=crimson gold amber divine. Footer=শুভ দীপাবলি—prosperity and light.',

        'Durga Puja' => 'Background=puja pandal crimson-gold glow. Hero=dhunuchi flame and dhak drums—Shakti energy. Graphic=traditional frame motif. Colors=crimson gold divine. Footer=শুভ শারদীয়া—goddess blessing.',

        'World Health Day' => 'Background=sunrise wellness gradient. Hero=globe with stethoscope sculptural 3D—universal care. Graphic=heartbeat line subtle. Colors=teal hope, white clinical trust. Footer=বিশ্ব স্বাস্থ্য দিবস—health for all message.',

        'World Pharmacists Day' => 'Background=soft lab bokeh premium. Hero=amber medicine bottles on tray—pharmacist expertise. Graphic=molecule hex at 8% opacity. Colors=gold-teal pharma luxury. Footer=pharmacist honour line—trust and care.',

        'Pharma Product Launch' => 'Background=dark-to-teal launch gradient. Hero=single product packshot pedestal spotlight—new era. Graphic=particle burst directional. Colors=teal innovation gold premium. Footer=launch date and product promise—commercial clarity.',

        'Black Friday' => 'Background=dark luxury studio. Hero=explosive percent burst or gift stack—urgency. Graphic=skewed yellow-black sale block. Colors=contrast urgency. Footer=offer deadline and CTA—every word drives action.',

        'National Mourning Day' => 'Background=grey-black gradient silence. Hero=black ribbon on white marble—15 August grief. Graphic=none or single vertical line. Colors=grey black white only. Footer=remembrance for Bangabandhu—no celebration elements.',

        'Happy New Year' => 'Background=fireworks over city midnight. Hero=champagne sparkle or "2026" numeral gold 3D. Graphic=year numeral as flat white block behind hero. Colors=gold midnight blue hope. Footer=new year wish and year digit—fresh start.',

        'Labour Day' => 'Background=industrial dawn or constructivist angles. Hero=worker silhouette with tool—dignity of labour. Graphic=red-yellow-black angular shapes. Colors=constructivist labour palette. Footer=May 1, worker solidarity message.',

        'Earth Day' => 'Background=still water reflection. Hero=lush tree mirrored—planet breathing. Graphic=circular earth arc. Colors=green blue natural. Footer=protect earth CTA—action not decoration.',

        'Merry Christmas' => 'Background=snow-frosted cabin warmth. Hero=pine with fairy lights—gift of light. Graphic=star or ornament geometry. Colors=red green gold cozy. Footer=শুভ বড়দিন—peace and giving.',

        'Cricket Victory Celebration' => 'Background=stadium roar green-red energy. Hero=trophy bat ball composition—national pride sport. Graphic=scoreboard numeral or wicket arc. Colors=Bangladesh green-red victory. Footer=match glory and fan thanks.',

        'Digital Bangladesh Day' => 'Background=tech dusk skyline. Hero=glowing circuit-board map of Bangladesh—innovation nation. Graphic=5G node constellation. Colors=teal magenta digital. Footer=vision 2041 smart nation—progress narrative.',

        'Default Custom Event' => 'Research this occasion name deeply. Background must tell where/when/why. Hero must be the one symbol the audience instantly associates. Graphic device must encode year, count, or core metaphor. Colors must match cultural emotion. Every empty text zone must receive meaningful Bangla/English lines—never filler lorem ipsum energy.',
    ],
];
