<?php

return [
    'masterPosterRaw' => 'Senior art-director Bengali brand social poster, landscape 16:9 widescreen, Cannes-grade composition, luxury pharmaceutical print finish, cinematic depth, intentional color hierarchy, golden-ratio focal placement, jewel-tone accents, soft lens bloom, razor-sharp commercial grade. Deliberate negative space engineered for extraordinary post-production typography—multi-line Bangla headline + English sub-copy perfectly matched to palette and mood. STRICT: render ZERO text, Bengali/English letters, numbers, URLs, logos, or watermarks in the image.',

    'posterTypeA' => [
        'Victory Day', 'Independence Day', 'International Mother Language Day', 'National Mourning Day',
        'Martyred Intellectuals Day', 'Bangabandhu Homecoming Day',
        'World TB Day', 'World AIDS Day', 'Human Rights Day',
    ],

    'posterStyleTemplates' => [
        'folk_bright' => 'Bright folk-art poster: solid light sky-blue background with soft center vignette, faint white Alpana ring pattern at bottom base. Center: handcrafted Mangal Shobhajatra-style masks and props with tactile 3D paper-mache presence, saturated green/red/orange/yellow patterns, soft shadows—not a night scene.',
        'patriotic_night_glow' => 'Epic patriotic night poster: deep navy starfield, dense white stars. Center: Jatiyo Smriti Soudho (National Martyrs\' Memorial), geometric concrete planes, vivid cyan electric rim glow, thin cyan horizon behind base, symmetric glowing white spherical lamps on dark reflective ground. Solemn symmetrical composition.',
        'patriotic_graphic' => 'Minimalist patriotic graphic poster: rich blue radial gradient background (lighter center). Left: tall white angular National Martyrs\' Memorial with light grey facet shading. Bottom: dark celebrating crowd silhouettes with raised arms; one detailed Bangladesh flag with folds emerging from silhouettes. Upper-right zone kept open for text.',
        'monument_dawn' => 'Solemn dawn tribute poster: soft purple-magenta sky, gentle god-rays. Center: Shaheed Minar with optional marigolds on steps, respectful mood, clean lower edge for verse overlay—not festive night vector.',
        'festive_night_vector' => 'Flat 2D vector night greeting: navy sky, crescent moon, stars, city skyline with yellow windows, fairy-light trees, warm gold accents. Foreground characters on dark ground—friendly geometric illustration style.',
        'cultural_burst' => 'Explosive color festival poster: dynamic composition, vivid primary pigments frozen mid-air or bold flat graphic shapes, dark or clean backdrop for contrast—celebratory not photoreal documentary.',
        'spring_pastel' => 'Soft spring poster: pastel mint/cream/yellow palette, marigolds and blossoms, airy morning light, generous top negative space.',
        'islamic_serenity' => 'Serene Islamic night: deep indigo, elegant minaret silhouettes, golden lantern glow, geometric arabesque accents—peaceful not crowded.',
        'neon_celebration' => 'Midnight celebration poster: dark base with neon gold/magenta/cyan accents, fireworks or confetti geometry, modern party energy.',
        'warm_family' => 'Warm emotional poster: golden-hour softness, intimate human connection, blush pink or amber tones, minimal clutter.',
        'nature_eco' => 'Clean eco poster: lush green hero element (tree, leaf, globe motif), mirror water or off-white recycled texture, hopeful daylight.',
        'monsoon_cozy' => 'Moody monsoon poster: deep blue-green, rain texture, cozy window or umbrella scene, nostalgic calm.',
        'beach_summer' => 'Tropical bright poster: turquoise and sand tones, sun and waves, energetic travel-magazine clarity.',
        'labour_bold' => 'Bold labour poster: constructivist angles, red/yellow/black, worker hero silhouette, industrial sparks optional.',
        'tourism_vintage' => 'Vintage travel poster: flat pastel landmarks, passport-stamp motifs, chic minimal wanderlust layout.',
        'academic_nostalgic' => 'Academic nostalgia: warm desk still-life—globe, books, apple—soft cinematic light, intellectual calm.',
        'halloween_playful' => 'Playful Halloween graphic: cute pumpkins and ghosts on vibrant purple-orange—not horror gore.',
        'sale_impact' => 'High-impact sale poster: dark luxury base, bold yellow/black or neon blocks, dynamic skewed shapes—retail urgency.',
        'harvest_warm' => 'Autumn harvest poster: pumpkins, corn, rustic wood, candle warmth, creamy beige background.',
        'christmas_cozy' => 'Cozy Christmas poster: snow-frosted pine, warm fairy lights, red-green accents, cabin warmth.',
        'mourning_solemn' => 'National mourning poster: muted grey-black gradient, black ribbon on white marble pillar, zero celebration, chiaroscuro respect.',
        'divine_indigo' => 'Spiritual indigo poster: glowing full moon, lotus or flute/matki motifs, symmetrical peaceful geometry.',
        'women_empower' => 'Empowerment poster: flowing purple/blush silhouettes in unity, modern minimal empowerment aesthetic.',
        'modern_celebration' => 'Modern celebration poster: clean graphic layout, occasion-specific hero object centered, balanced color story unique to the event.',
        'sports_broadcast' => 'Premium sports broadcast poster 16:9: floodlit stadium or arena photographic background; photoreal gold trophy or ball hero centred as spine; bold flat white year numerals behind hero (broadcast graphics); lower third dark gradient for hosts+dates—every layer purposeful like FIFA World Cup reference art.',
        // —— Pharma & healthcare WOW styles ——
        'pharma_premium' => 'Ultra-premium pharmaceutical poster: clinical white-to-teal gradient, soft bokeh glass vials and capsule silhouettes, molecular hex mesh at 8% opacity, golden rim light, Swiss-grid symmetry, top 32% pristine empty for Bangla headline—looks like a Fortune-500 health brand campaign.',
        'pharma_trust' => 'Trust-building health poster: caring doctor-nurse silhouette with patient, subtle ECG heartbeat line, deep trustworthy navy and healing emerald, soft vignette, lens flare at corner—professional, warm, never clip-art cheap.',
        'pharma_wellness' => 'Wellness lifestyle poster: joyful Bangladeshi family outdoors, fresh greens and morning sun, optimistic health narrative, generous headline zone, magazine-cover polish.',
        'pharma_awareness' => 'Awareness ribbon poster: iconic cause ribbon or symbolic hero (heart, pink ribbon, red ribbon) as sculptural 3D object on clean gradient, dramatic spotlight, emotional but dignified.',
        'pharma_lab' => 'Science excellence poster: microscope, petri dish, DNA helix abstract in teal-gold, dark navy lab mood with neon edge lights, futuristic yet credible.',
        'corporate_summit' => 'Corporate excellence poster: glass tower reflection, gold accent line, minimalist navy, executive polish, wide negative space for bilingual CEO message.',
        'industrial_power' => 'Industrial strength poster: metallics, safety orange accents, bold geometric momentum, factory/agro silhouette optional.',
        'retail_mega' => 'Retail mega-sale poster: explosive offer energy, brand magenta/cyan or gold-black luxury sale, dynamic diagonal shapes.',
        'real_estate_luxe' => 'Real estate luxury poster: aerial skyline golden hour, architectural model glow, deep blue prestige, empty lower band for project name.',
        'telecom_future' => 'Telecom future poster: 5G wave geometry, electric blue-magenta gradient, connectivity nodes, sleek tech WOW.',
        'textile_craft' => 'Textile craft poster: jamdani weave pattern macro, rich maroon-gold, artisan loom silhouette, heritage luxury.',
        'agro_harvest' => 'Agro harvest poster: golden paddy field, fertilizer bag silhouette stylized, sunrise optimism, green-gold palette.',
    ],

    'posterStyleByOccasion' => [
        'Pohela Boishakh' => 'folk_bright',
        'Victory Day' => 'patriotic_night_glow',
        'Independence Day' => 'patriotic_graphic',
        'International Mother Language Day' => 'monument_dawn',
        'National Mourning Day' => 'mourning_solemn',
        'Eid ul-Fitr' => 'festive_night_vector',
        'Eid ul-Adha' => 'festive_night_vector',
        'Ramadan Kareem' => 'islamic_serenity',
        'Islamic New Year' => 'islamic_serenity',
        'Holi Festival' => 'cultural_burst',
        'Diwali Festival' => 'cultural_burst',
        'Durga Puja' => 'cultural_burst',
        'Spring Festival (Bosonto)' => 'spring_pastel',
        'Easter Sunday' => 'spring_pastel',
        'Happy New Year' => 'neon_celebration',
        'New Year\'s Eve' => 'neon_celebration',
        'Chinese New Year' => 'neon_celebration',
        'Valentine\'s Day' => 'warm_family',
        'Mother\'s Day' => 'warm_family',
        'Father\'s Day' => 'warm_family',
        'Earth Day' => 'nature_eco',
        'World Environment Day' => 'nature_eco',
        'Monsoon Festival' => 'monsoon_cozy',
        'Summer Vibes' => 'beach_summer',
        'Labour Day' => 'labour_bold',
        'World Tourism Day' => 'tourism_vintage',
        'Teacher\'s Day' => 'academic_nostalgic',
        'Halloween' => 'halloween_playful',
        'Black Friday' => 'sale_impact',
        'Singles Day (11.11)' => 'sale_impact',
        'Thanksgiving' => 'harvest_warm',
        'Merry Christmas' => 'christmas_cozy',
        'Friendship Day' => 'modern_celebration',
        'Janmashtami' => 'divine_indigo',
        'Buddha Purnima' => 'divine_indigo',
        'International Women\'s Day' => 'women_empower',
        'Makar Sankranti' => 'cultural_burst',
        'Autumn Festival (Kashful)' => 'spring_pastel',
        // Pharma & health
        'World Health Day' => 'pharma_wellness',
        'World TB Day' => 'pharma_awareness',
        'World Malaria Day' => 'pharma_awareness',
        'World Immunization Week' => 'pharma_trust',
        'International Nurses Day' => 'pharma_trust',
        'World Heart Day' => 'pharma_awareness',
        'World Pharmacists Day' => 'pharma_premium',
        'World Mental Health Day' => 'pharma_wellness',
        'World Cancer Awareness' => 'pharma_awareness',
        'World Diabetes Day' => 'pharma_awareness',
        'World AIDS Day' => 'pharma_awareness',
        'World ORS Day' => 'pharma_wellness',
        'Hand Hygiene Day' => 'pharma_premium',
        'National Vitamin-A Campaign' => 'pharma_wellness',
        'Blood Donation Day' => 'pharma_trust',
        'Doctor\'s Day Bangladesh' => 'pharma_trust',
        'Antibiotic Awareness Week' => 'pharma_lab',
        'Pharmacy Week Bangladesh' => 'pharma_premium',
        'Generic Medicine Awareness' => 'pharma_premium',
        'Pharma Product Launch' => 'pharma_premium',
        'CSR Health Camp' => 'pharma_wellness',
        // Industries
        'Corporate Anniversary' => 'corporate_summit',
        'Employee Appreciation Day' => 'corporate_summit',
        'Quality Excellence Day' => 'corporate_summit',
        'FMCG Mega Promo' => 'retail_mega',
        'Garments & Textile Expo' => 'textile_craft',
        'Agro & Fertilizer Season' => 'agro_harvest',
        'Telecom 5G Launch' => 'telecom_future',
        'Real Estate Project Launch' => 'real_estate_luxe',
        'Insurance Awareness Day' => 'corporate_summit',
        'Banking & Finance Day' => 'corporate_summit',
        'Export Summit Bangladesh' => 'corporate_summit',
        'Digital Bangladesh Day' => 'telecom_future',
        'Startup Innovation Day' => 'telecom_future',
        'Construction Safety Week' => 'industrial_power',
        // Bangladeshi & South Asian
        'Pahela Falgun' => 'spring_pastel',
        'Chand Raat' => 'festive_night_vector',
        'Shab-e-Barat' => 'islamic_serenity',
        'Laylat al-Qadr (Shab-e-Qadr)' => 'islamic_serenity',
        'Ashura (10 Muharram)' => 'mourning_solemn',
        'Milad un-Nabi (Eid-e-Milad)' => 'islamic_serenity',
        'Mawlid Celebration' => 'islamic_serenity',
        'Martyred Intellectuals Day' => 'mourning_solemn',
        'National Children\'s Day' => 'spring_pastel',
        'Bangabandhu Homecoming Day' => 'patriotic_graphic',
        'Lakshmi Puja' => 'cultural_burst',
        'Kali Puja' => 'cultural_burst',
        'Saraswati Puja (Basant Panchami)' => 'academic_nostalgic',
        'Navratri' => 'cultural_burst',
        'Raksha Bandhan' => 'warm_family',
        'Bhai Phota (Bhai Dooj)' => 'warm_family',
        'Onam Festival' => 'spring_pastel',
        'Chhath Puja' => 'divine_indigo',
        'Maha Shivratri' => 'divine_indigo',
        'Good Friday' => 'mourning_solemn',
        'Christmas Eve' => 'christmas_cozy',
        'Human Rights Day' => 'modern_celebration',
        'World Water Day' => 'nature_eco',
        'World Food Day' => 'harvest_warm',
        'International Yoga Day' => 'nature_eco',
        'Gandhi Jayanti' => 'modern_celebration',
        'World Children\'s Day' => 'spring_pastel',
        // Retail & campaigns
        'Eid Mega Sale' => 'sale_impact',
        'Puja Mega Sale' => 'sale_impact',
        'Cyber Monday' => 'sale_impact',
        'Summer Mega Sale' => 'sale_impact',
        'Winter Mega Sale' => 'sale_impact',
        'Back to School Campaign' => 'modern_celebration',
        'Wedding Season Campaign' => 'warm_family',
        'Ramadan Iftar Campaign' => 'warm_family',
        'New Store Opening' => 'retail_mega',
        'Grand Opening Sale' => 'retail_mega',
        'Flash Sale Weekend' => 'sale_impact',
        'Cricket Victory Celebration' => 'sports_broadcast',
        'Football World Cup Fever' => 'sports_broadcast',
        'FIFA World Cup 2026' => 'sports_broadcast',
        'National Sports Day' => 'sports_broadcast',
        'Olympic Spirit Day' => 'sports_broadcast',
        'World Athletics Day' => 'sports_broadcast',
    ],
];
