<?php

return [
    [
        'id' => 'Tube Light',
        'icon' => '📏',
        'label' => 'Tube Light (ceiling / wall)',
        'val' => 'Tube light installed and glowing on the ceiling or wall',
        'keywords' => ['tube', 'batten', 't5', 't8'],
        'backgrounds' => [
            ['label' => '🍳 Modern Kitchen', 'val' => 'Bright modern kitchen with tube lights glowing on the ceiling'],
            ['label' => '🚿 Washroom', 'val' => 'Clean modern washroom lit by ceiling tube lights'],
            ['label' => '💼 Office Space', 'val' => 'Professional office space lit by ceiling tube lights'],
            ['label' => '🏬 Commercial Space', 'val' => 'Spacious commercial space lit by ceiling tube lights'],
            ['label' => '🅿️ Garage / Workshop', 'val' => 'Tidy garage workshop lit by ceiling tube lights'],
            ['label' => '🪞 Bathroom Mirror (wall)', 'val' => 'Bathroom vanity mirror lit by a wall-mounted tube light'],
            ['label' => '🍽️ Under-Cabinet (wall)', 'val' => 'Modern kitchen with wall-mounted under-cabinet tube lights glowing'],
            ['label' => '🛋️ Living Room Wall', 'val' => 'Living room with a wall-mounted tube light glowing along the wall'],
            ['label' => '🛏️ Bedroom Wall', 'val' => 'Cozy bedroom with a wall-mounted tube light glowing above the headboard'],
        ],
    ],
    [
        'id' => 'LED Panel',
        'icon' => '🔲',
        'label' => 'LED Panel (ceiling)',
        'val' => 'LED panel light fitted in the ceiling, switched on',
        'keywords' => ['panel', 'ceiling panel', 'flat panel', 'slim panel'],
        'backgrounds' => [
            ['label' => '💼 Office Space', 'val' => 'Modern office with recessed LED ceiling panels glowing'],
            ['label' => '🏬 Commercial Space', 'val' => 'Retail commercial space lit by LED ceiling panels'],
            ['label' => '🏥 Clinic / Hospital', 'val' => 'Clean clinic interior with bright LED ceiling panels'],
            ['label' => '🏫 Classroom', 'val' => 'Bright classroom lit by LED ceiling panels'],
            ['label' => '🍳 Modern Kitchen', 'val' => 'Modern kitchen with LED ceiling panel lighting'],
        ],
    ],
    [
        'id' => 'Downlights',
        'icon' => '🔆',
        'label' => 'Recessed Downlights',
        'val' => 'Recessed downlights lighting up the room',
        'keywords' => ['downlight', 'recessed'],
        'backgrounds' => [
            ['label' => '🛋️ Living Room', 'val' => 'Cozy modern living room lit by recessed downlights'],
            ['label' => '🍳 Modern Kitchen', 'val' => 'Modern kitchen lit by recessed ceiling downlights'],
            ['label' => '🏨 Hotel Lobby', 'val' => 'Elegant hotel lobby lit by recessed downlights'],
            ['label' => '🍽️ Restaurant / Cafe', 'val' => 'Warm restaurant interior lit by recessed downlights'],
            ['label' => '🛏️ Cozy Bedroom', 'val' => 'Warm cozy bedroom lit by recessed downlights'],
        ],
    ],
    [
        'id' => 'Pendant Bulb',
        'icon' => '💡',
        'label' => 'Pendant Bulb',
        'val' => 'Glowing bulbs in pendant fixtures over the table',
        'keywords' => ['bulb', 'pendant', 'smart rgb', 'led bulb'],
        'backgrounds' => [
            ['label' => '👨‍👩‍👧 Family Dining', 'val' => 'Family dining room with glowing pendant bulbs over the table'],
            ['label' => '🍽️ Restaurant / Cafe', 'val' => 'Cozy restaurant with pendant bulb lights over the tables'],
            ['label' => '🍳 Kitchen Island', 'val' => 'Modern kitchen island with glowing pendant bulb lights'],
            ['label' => '🛋️ Living Room', 'val' => 'Stylish living room with pendant bulb lighting'],
        ],
    ],
    [
        'id' => 'String Lights',
        'icon' => '✨',
        'label' => 'String / Fairy Lights',
        'val' => 'Warm string lights strung across the space, glowing',
        'keywords' => ['string', 'fairy'],
        'backgrounds' => [
            ['label' => '🏡 Patio Gazebo (Night)', 'val' => 'Cozy outdoor wooden patio gazebo at night with warm string lights strung across, glowing'],
            ['label' => '🌳 Garden / Backyard', 'val' => 'Garden backyard at night with warm string lights overhead'],
            ['label' => '🏙️ Rooftop Terrace', 'val' => 'Rooftop terrace at night with warm string lights strung across'],
            ['label' => '💍 Outdoor Event', 'val' => 'Outdoor evening event space with warm string lights overhead'],
            ['label' => '🪟 Balcony', 'val' => 'Cozy balcony at night with warm string lights'],
        ],
    ],
    [
        'id' => 'Wall Light',
        'icon' => '🛋️',
        'label' => 'Wall Light / Sconce',
        'val' => 'Wall-mounted light glowing on the wall',
        'keywords' => ['wall light', 'sconce'],
        'backgrounds' => [
            ['label' => '🛋️ Living Room', 'val' => 'Modern living room with wall-mounted lights glowing'],
            ['label' => '🏨 Hotel Lobby', 'val' => 'Elegant hotel lobby with wall sconces glowing'],
            ['label' => '🛏️ Cozy Bedroom', 'val' => 'Cozy bedroom with wall-mounted bedside lights glowing'],
            ['label' => '🚪 Hallway', 'val' => 'Modern hallway lit by wall-mounted lights'],
            ['label' => '🪜 Staircase', 'val' => 'Stylish staircase lit by wall-mounted lights'],
        ],
    ],
    [
        'id' => 'Halogen Sports Floodlight',
        'icon' => '🏟️',
        'label' => 'Halogen Sports Floodlight',
        'val' => 'Halogen floodlights mounted high, brightly illuminating the court',
        'keywords' => ['halogen', 'badminton', 'sports flood', 'stadium'],
        'backgrounds' => [
            ['label' => '🏸 Badminton Court', 'val' => 'Indoor badminton court brightly lit by overhead halogen floodlights'],
            ['label' => '🎾 Tennis Court', 'val' => 'Outdoor tennis court at night lit by tall halogen floodlights'],
            ['label' => '🏀 Basketball Court', 'val' => 'Indoor basketball court lit by bright overhead floodlights'],
            ['label' => '🏟️ Football Stadium', 'val' => 'Football stadium at night lit by powerful floodlight towers'],
            ['label' => '🏏 Cricket Ground', 'val' => 'Cricket ground at night under bright stadium floodlights'],
        ],
    ],
    [
        'id' => 'Outdoor Flood Light',
        'icon' => '🏢',
        'label' => 'Outdoor Flood Light',
        'val' => 'Flood lights mounted and washing the area with bright light',
        'keywords' => ['flood light', 'floodlight', 'outdoor flood', 'weatherproof'],
        'backgrounds' => [
            ['label' => '🏢 Building Facade', 'val' => 'Building facade at night lit up by mounted flood lights'],
            ['label' => '🅿️ Parking Lot', 'val' => 'Outdoor parking lot at night lit by flood lights'],
            ['label' => '🏭 Warehouse Yard', 'val' => 'Warehouse yard at night illuminated by flood lights'],
            ['label' => '🌳 Garden Landscape', 'val' => 'Garden landscape at night washed with flood lighting'],
            ['label' => '🪧 Billboard / Signage', 'val' => 'Large outdoor billboard lit by flood lights at night'],
        ],
    ],
    [
        'id' => 'High Bay Light',
        'icon' => '🏭',
        'label' => 'High Bay Light',
        'val' => 'High bay lights suspended from a tall ceiling, illuminating below',
        'keywords' => ['high bay', 'warehouse'],
        'backgrounds' => [
            ['label' => '🏭 Factory Floor', 'val' => 'Industrial factory floor lit by high bay lights from a tall ceiling'],
            ['label' => '📦 Warehouse', 'val' => 'Large warehouse lit by rows of high bay lights'],
            ['label' => '🤾 Indoor Gymnasium', 'val' => 'Indoor sports gymnasium lit by high bay lights'],
            ['label' => '🛒 Mall Atrium', 'val' => 'Shopping mall atrium lit by high bay lights'],
            ['label' => '✈️ Aircraft Hangar', 'val' => 'Aircraft hangar interior lit by high bay lights'],
        ],
    ],
    [
        'id' => 'Street Light',
        'icon' => '🌃',
        'label' => 'Street Light',
        'val' => 'Street lights mounted on poles, illuminating the road at night',
        'keywords' => ['street', 'pole light'],
        'backgrounds' => [
            ['label' => '🌃 City Street', 'val' => 'City street at night illuminated by rows of street lights'],
            ['label' => '🛣️ Highway', 'val' => 'Highway at night lit by tall street lights'],
            ['label' => '🏘️ Residential Road', 'val' => 'Quiet residential road at night lit by street lights'],
            ['label' => '🌳 Park Pathway', 'val' => 'Park pathway at night lit by garden street lamps'],
            ['label' => '🅿️ Parking Lot', 'val' => 'Parking lot at night lit by pole-mounted street lights'],
        ],
    ],
    [
        'id' => 'Spotlight / Track',
        'icon' => '🎯',
        'label' => 'Spotlight / Track Light',
        'val' => 'Spotlights and track lights highlighting objects on display',
        'keywords' => ['spotlight', 'track light'],
        'backgrounds' => [
            ['label' => '🖼️ Art Gallery', 'val' => 'Art gallery with spotlights highlighting framed artworks'],
            ['label' => '🛍️ Retail Store', 'val' => 'Modern retail store with track lights highlighting products'],
            ['label' => '🏛️ Museum', 'val' => 'Museum exhibit lit by focused spotlights'],
            ['label' => '🚗 Showroom', 'val' => 'Car showroom with spotlights highlighting a vehicle'],
            ['label' => '💍 Jewelry Display', 'val' => 'Jewelry display case lit by bright focused spotlights'],
        ],
    ],
    [
        'id' => 'Garden / Landscape',
        'icon' => '🪴',
        'label' => 'Garden / Landscape Light',
        'val' => 'Landscape lights placed along the ground, glowing softly',
        'keywords' => ['landscape', 'garden light'],
        'backgrounds' => [
            ['label' => '🪴 Garden Path', 'val' => 'Garden pathway at night lined with glowing landscape lights'],
            ['label' => '🏡 Building Entrance', 'val' => 'Building entrance at night lit by landscape lights'],
            ['label' => '🏊 Poolside', 'val' => 'Poolside at night lit by soft landscape lights'],
            ['label' => '🚗 Driveway', 'val' => 'Driveway at night lined with landscape lights'],
            ['label' => '🌳 Backyard', 'val' => 'Backyard garden at night with glowing landscape lighting'],
        ],
    ],
    [
        'id' => 'Pool / Underwater',
        'icon' => '🏊',
        'label' => 'Pool / Underwater Light',
        'val' => 'Underwater lights glowing beneath the water surface',
        'keywords' => ['pool', 'underwater'],
        'backgrounds' => [
            ['label' => '🏊 Swimming Pool', 'val' => 'Swimming pool at night glowing with underwater lights'],
            ['label' => '⛲ Fountain', 'val' => 'Decorative fountain glowing with underwater lights at night'],
            ['label' => '🛁 Spa / Jacuzzi', 'val' => 'Luxury spa jacuzzi glowing with underwater lighting'],
            ['label' => '💧 Water Feature', 'val' => 'Garden water feature glowing with underwater lights'],
        ],
    ],
    [
        'id' => 'Chandelier',
        'icon' => '💎',
        'label' => 'Chandelier',
        'val' => 'An elegant chandelier hanging and glowing from the ceiling',
        'keywords' => ['chandelier'],
        'backgrounds' => [
            ['label' => '🎉 Banquet Hall', 'val' => 'Grand banquet hall with a glowing chandelier overhead'],
            ['label' => '🏨 Hotel Lobby', 'val' => 'Luxury hotel lobby with an elegant glowing chandelier'],
            ['label' => '🍽️ Dining Room', 'val' => 'Elegant dining room with a glowing chandelier over the table'],
            ['label' => '💃 Ballroom', 'val' => 'Ballroom with a sparkling chandelier lighting the room'],
            ['label' => '🪜 Grand Staircase', 'val' => 'Grand staircase lit by a hanging chandelier'],
        ],
    ],
    [
        'id' => 'Table / Desk Lamp',
        'icon' => '🛋️',
        'label' => 'Table / Desk Lamp',
        'val' => 'A table lamp switched on, casting a warm pool of light',
        'keywords' => ['table lamp', 'desk lamp'],
        'backgrounds' => [
            ['label' => '📚 Study Desk', 'val' => 'Study desk at night with a glowing table lamp'],
            ['label' => '🛏️ Bedside Table', 'val' => 'Bedside table at night with a warm glowing lamp'],
            ['label' => '💼 Office Desk', 'val' => 'Modern office desk with a desk lamp switched on'],
            ['label' => '📖 Reading Nook', 'val' => 'Cozy reading nook lit by a warm table lamp'],
        ],
    ],
    [
        'id' => 'Emergency / Exit',
        'icon' => '🚪',
        'label' => 'Emergency / Exit Light',
        'val' => 'Emergency exit lights glowing along the route',
        'keywords' => ['emergency', 'exit light'],
        'backgrounds' => [
            ['label' => '🚪 Corridor', 'val' => 'Building corridor with glowing emergency exit lights'],
            ['label' => '🪜 Stairwell', 'val' => 'Stairwell lit by emergency exit lights'],
            ['label' => '🏢 Office Exit', 'val' => 'Office exit route lit by emergency lights'],
            ['label' => '🅿️ Parking Garage', 'val' => 'Underground parking garage lit by emergency lights'],
        ],
    ],
];
