<?php

return [
    'form_banner' => 'Follow the chain: Step 01 product type → Step 04 how it installs → Step 05 which room → Step 07 where the hero cutout sits in the frame. Lights mount in ceiling/wall; switches mount on wall plates with room lights ON.',

    'step01_label' => 'What light or switch are you selling?',
    'step01_guide' => 'Use the exact product type from your reference image. Bulbs and panels install in ceilings; switches mount on wall plates. Wrong type here causes AI to render the wrong product.',
    'step01_placeholder' => 'E.g. 6A Modular 1-Way Switch, 18W LED Panel Light, Smart WiFi Touch Switch...',
    'step01_example' => 'Switch example: "Modular 2-Way Staircase Switch" · Light example: "18W Slim LED Ceiling Panel Light"',

    'product_suggestions' => [
        ['icon' => '💡', 'label' => 'LED Bulb', 'value' => '9W Energy-Saving LED Bulb E27', 'category' => 'lights'],
        ['icon' => '🔲', 'label' => 'Panel Light', 'value' => '18W Slim LED Ceiling Panel Light', 'category' => 'lights'],
        ['icon' => '📏', 'label' => 'Tube Light', 'value' => '20W LED Tube Batten Light T5', 'category' => 'lights'],
        ['icon' => '🔆', 'label' => 'Downlight', 'value' => '7W Recessed LED Downlight', 'category' => 'lights'],
        ['icon' => '🎯', 'label' => 'Spotlight', 'value' => '12W Adjustable LED Spotlight', 'category' => 'lights'],
        ['icon' => '🔦', 'label' => 'Focus Light', 'value' => 'Adjustable LED Focus Light with Narrow Beam', 'category' => 'lights'],
        ['icon' => '🌈', 'label' => 'Smart Bulb', 'value' => 'Smart RGB WiFi LED Bulb', 'category' => 'lights'],
        ['icon' => '✨', 'label' => 'String Lights', 'value' => 'Outdoor Waterproof String Lights', 'category' => 'lights'],
        ['icon' => '🌦️', 'label' => 'Flood Light', 'value' => '50W Weatherproof LED Flood Light', 'category' => 'lights'],
        ['icon' => '🛋️', 'label' => 'Table Lamp', 'value' => 'Modern LED Table Lamp', 'category' => 'lights'],
        ['icon' => '💎', 'label' => 'Chandelier', 'value' => 'Decorative LED Chandelier', 'category' => 'lights'],
        ['icon' => '🏟️', 'label' => 'High Bay', 'value' => '150W Industrial LED High Bay Light', 'category' => 'lights'],
        ['icon' => '🌃', 'label' => 'Street Light', 'value' => 'LED Street Light Pole Fixture', 'category' => 'lights'],
        ['icon' => '🔘', 'label' => '1-Way Switch', 'value' => '6A Modular 1-Way Wall Switch', 'category' => 'switches'],
        ['icon' => '🔀', 'label' => '2-Way Switch', 'value' => '6A Modular 2-Way Staircase Switch', 'category' => 'switches'],
        ['icon' => '📱', 'label' => 'Smart WiFi', 'value' => 'Smart WiFi Touch Wall Switch 10A', 'category' => 'switches'],
        ['icon' => '🌗', 'label' => 'Dimmer', 'value' => 'LED Compatible Dimmer Switch', 'category' => 'switches'],
        ['icon' => '🌀', 'label' => 'Fan Regulator', 'value' => 'Ceiling Fan Speed Regulator Switch', 'category' => 'switches'],
        ['icon' => '👆', 'label' => 'Touch Panel', 'value' => 'Premium Glass Touch Panel Switch', 'category' => 'switches'],
        ['icon' => '🔔', 'label' => 'Bell Push', 'value' => 'Doorbell Bell Push Switch', 'category' => 'switches'],
        ['icon' => '👁️', 'label' => 'PIR Sensor', 'value' => 'PIR Motion Sensor Auto Switch', 'category' => 'switches'],
        ['icon' => '🔌', 'label' => 'Socket + Switch', 'value' => 'Combined 5A Socket and Switch Plate', 'category' => 'switches'],
        ['icon' => '⚡', 'label' => 'MCB Panel', 'value' => 'MCB Distribution Switch Panel', 'category' => 'switches'],
        ['icon' => '📡', 'label' => 'Remote Switch', 'value' => 'Wireless Remote Light Switch Kit', 'category' => 'switches'],
        ['icon' => '🏨', 'label' => 'Card Key', 'value' => 'Hotel Card Key Energy Saver Switch', 'category' => 'switches'],
        ['icon' => '🎛️', 'label' => 'Multi-Gang', 'value' => '4-Gang Modular Switch Plate', 'category' => 'switches'],
    ],

    'step03_label' => 'Marketing headline text',
    'step03_guide' => 'Short bold headline only — 1 to 3 selling points max. These appear as poster text, not long paragraphs.',
    'step03_placeholder' => 'E.g. ENERGY SAVING · LONG LIFESPAN · MODERN DESIGN',
    'step03_example' => 'Switch: "SAFE SWITCHING · FIRE RETARDANT BODY" · Light: "BRIGHT UNIFORM LIGHT · ENERGY SAVING"',

    'marketing_chips' => [
        ['icon' => '⚡', 'label' => 'Energy Saving', 'value' => 'ENERGY SAVING PERFORMANCE', 'match' => 'ENERGY SAVING', 'category' => 'lights'],
        ['icon' => '🔆', 'label' => 'Bright & Uniform', 'value' => 'BRIGHT & UNIFORM ILLUMINATION', 'match' => 'BRIGHT', 'category' => 'lights'],
        ['icon' => '⏳', 'label' => 'Long Lifespan', 'value' => 'LONG LIFESPAN UP TO 25000 HOURS', 'match' => 'LIFESPAN', 'category' => 'lights'],
        ['icon' => '💎', 'label' => 'Modern Design', 'value' => 'MODERN & ELEGANT DESIGN', 'match' => 'ELEGANT', 'category' => 'lights'],
        ['icon' => '🔧', 'label' => 'Easy Install', 'value' => 'EASY INSTALLATION', 'match' => 'INSTALLATION', 'category' => 'lights'],
        ['icon' => '🍳', 'label' => 'Kitchen & Bath', 'value' => 'PERFECT FOR KITCHENS & WASHROOMS', 'match' => 'KITCHENS', 'category' => 'lights'],
        ['icon' => '🏠', 'label' => 'Home & Office', 'value' => 'IDEAL FOR HOMES & OFFICES', 'match' => 'HOMES', 'category' => 'lights'],
        ['icon' => '🔘', 'label' => 'Safe Switching', 'value' => 'SAFE & RELIABLE SWITCHING', 'match' => 'SAFE', 'category' => 'switches'],
        ['icon' => '📱', 'label' => 'Smart Control', 'value' => 'SMART APP & VOICE CONTROL', 'match' => 'SMART', 'category' => 'switches'],
        ['icon' => '🛡️', 'label' => 'Fire Retardant', 'value' => 'FIRE RETARDANT SWITCH BODY', 'match' => 'FIRE RETARDANT', 'category' => 'switches'],
        ['icon' => '👆', 'label' => 'Touch Control', 'value' => 'PREMIUM TOUCH CONTROL', 'match' => 'TOUCH', 'category' => 'switches'],
        ['icon' => '🌗', 'label' => 'Dimmer Ready', 'value' => 'SMOOTH DIMMING CONTROL', 'match' => 'DIMMING', 'category' => 'switches'],
    ],

    'usage_categories' => [
        'lights' => ['label' => 'Home & office lights', 'icon' => '💡'],
        'switches' => ['label' => 'Wall switches & controls', 'icon' => '🔘'],
    ],

    'step04_example' => 'Pick install type below — Step 05 loads matching scene examples in the dropdown.',

    'step05_label' => 'Scene setting',
    'step05_guide' => 'Where Step 04 happens. Open the dropdown and use ↑ ↓ arrows + Enter, or type your own scene. Switches: wall plate visible with room lights ON.',
    'step05_placeholder' => 'E.g. Retail store with spotlights on product display',
    'step05_example' => 'Spotlight → gallery or showroom · Pendant → dining or kitchen · Switch → bedroom with wall plate and lights ON.',
    'step05_suggestions_label' => 'Suggested scenes',
    'step05_dropdown_placeholder' => 'Select suggested scene...',

    'step06_label' => 'Camera style (for video)',
    'step06_guide' => 'How the camera moves in the final video ad. Static poster shots work with slow orbit or gentle push-in.',
    'step06_placeholder' => 'E.g. Slow cinematic push-in toward the wall switch and glowing room...',

    'step07_label' => 'Product positioning',
    'step07_guide' => 'Where the hero product cutout sits in the poster frame. Use left or right to leave space for headline text. Scene fills the background.',
    'step07_placeholder' => 'E.g. Product on the right side. Space on left for text.',

    'step08_label' => 'Scene lighting & color mood',
    'step08_guide' => 'Color temperature and glow from the light product in the scene — warm home, cool office, night demo, dimmed dining, etc. For switches, show the warm/cool glow of the lights they control when ON.',
    'step08_placeholder' => 'E.g. Warm 3000K glow from ceiling LED, cozy home evening mood...',

    'lighting_style_chips' => [
        ['icon' => '🔥', 'label' => 'Warm White', 'value' => 'Warm white 3000K glow from ceiling light or bulb, cozy residential indoor mood'],
        ['icon' => '☀️', 'label' => 'Cool Daylight', 'value' => 'Cool daylight 6500K from panel or tube light, crisp bright office mood'],
        ['icon' => '⚪', 'label' => 'Neutral White', 'value' => 'Neutral 4000K balanced white from LED fixture, clean kitchen or washroom mood'],
        ['icon' => '🔆', 'label' => 'Bright Uniform', 'value' => 'Bright even LED panel or downlight illumination filling the room with no dark corners'],
        ['icon' => '🌙', 'label' => 'Night Demo', 'value' => 'Dark room at night with LED product as the only light source, realistic shadows and spill'],
        ['icon' => '🌗', 'label' => 'Dimmed Warm', 'value' => 'Soft dimmed warm light from dimmer-controlled pendant or chandelier, romantic dining mood'],
        ['icon' => '🏬', 'label' => 'Commercial', 'value' => 'Clean bright commercial LED lighting, professional neutral white for shop or office'],
        ['icon' => '✨', 'label' => 'Accent Beam', 'value' => 'Focused accent beam from spotlight or downlight highlighting product area with soft falloff'],
        ['icon' => '🏡', 'label' => 'Cozy Home', 'value' => 'Inviting warm home glow from ceiling or wall light, soft reflections on walls and furniture'],
        ['icon' => '🍽️', 'label' => 'Dining Glow', 'value' => 'Warm pendant or chandelier light over dining table, golden comfortable mealtime ambience'],
        ['icon' => '🌦️', 'label' => 'Outdoor Flood', 'value' => 'Cool white floodlight or street light beam washing outdoor area at night, sharp visibility'],
        ['icon' => '🌅', 'label' => 'Golden Evening', 'value' => 'Golden evening warmth from interior LED mixing with soft sunset tone through windows'],
    ],
];
